import { useCallback, useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { BrowserRouter, Link, Navigate, NavLink, Route, Routes, useLocation, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { BookmarkSimple, CheckCircle, Clock, Compass, Copy, Heart, IdentificationCard, MagnifyingGlass, MapPin, Question, ShieldCheck, UserCircle } from '@phosphor-icons/react'
import { api, del, patch, post } from './lib/api'

type SessionUser = { id: string; personal_email: string; first_name: string; last_name: string; city: string; work_email: string | null; verified: boolean }
type Profile = SessionUser & { mobile: string | null; sms_consent: boolean; educator_verified_at: string | null; member_id: string; estimated_savings_cents: number; reported_uses: number }
type Deal = { id: string; title: string; description: string; channel: 'in_person' | 'online'; category: string; restrictions: string; estimated_savings_cents: number; featured: boolean; sponsored: boolean; giveaway: boolean; business_id: string; business_name: string; business_description: string; image_url: string; website_url: string | null; distance: string | null; hours: string | null; is_open: boolean | null; address: string | null; latitude: number | null; longitude: number | null; saved?: boolean }
type Card = { member_id: string; teacherName: string; verified: boolean; status: string; walletStatus: 'available' | 'active' | 'failed' | 'pending' | 'not_configured'; walletDownloadUrl: string | null }

const GOLD = '#D4AF37', INK = '#0F172A'
const money = (cents: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(cents / 100)

function Logo({ light = false }: { light?: boolean }) {
  return <Link to="/deals" className="brand" aria-label="TeachersVIP home"><span className="brand-mark">TV</span><span style={{ color: light ? '#fff' : INK }}>Teachers</span><span style={{ color: GOLD }}>VIP</span></Link>
}
function Button({ children, variant = 'gold', type = 'button', disabled, onClick }: { children: ReactNode; variant?: 'gold' | 'navy' | 'soft' | 'danger'; type?: 'button' | 'submit'; disabled?: boolean; onClick?: () => void }) { return <button type={type} disabled={disabled} onClick={onClick} className={`action action-${variant}`}>{children}</button> }
function Field({ label, name, type = 'text', required, defaultValue, placeholder, minLength, readOnly = false }: { label: string; name: string; type?: string; required?: boolean; defaultValue?: string; placeholder?: string; minLength?: number; readOnly?: boolean }) { return <label className="field"><span>{label}</span><input name={name} type={type} required={required} defaultValue={defaultValue} placeholder={placeholder} minLength={minLength} readOnly={readOnly} />{readOnly && <small className="field-note">Managed through your account sign-in.</small>}</label> }
function Notice({ kind = 'info', children }: { kind?: 'info' | 'error' | 'success'; children: ReactNode }) { return <div className={`notice notice-${kind}`} role={kind === 'error' ? 'alert' : 'status'}>{children}</div> }
function AuthFrame({ children, title, intro }: { children: ReactNode; title: string; intro: string }) { return <main className="auth-page"><section className="auth-card"><Logo light /><div className="shield">✓</div><h1>{title}</h1><p>{intro}</p>{children}<small>Free for educators. Always.</small></section></main> }

function Register({ refresh }: { refresh: () => Promise<void> }) {
  const navigate = useNavigate(), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(''); const data = new FormData(event.currentTarget); try { await post('/auth/register', { firstName: data.get('firstName'), lastName: data.get('lastName'), personalEmail: data.get('personalEmail'), mobile: data.get('mobile') || undefined, city: data.get('city'), password: data.get('password'), smsConsent: data.get('smsConsent') === 'on' }); await refresh(); window.location.assign('/verify') } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  return <AuthFrame title="Welcome, Educators" intro="Create your free TeachersVIP account to access exclusive deals, giveaways and local perks."><form className="form-grid" onSubmit={submit}><div className="two"><Field label="First name" name="firstName" required minLength={2} /><Field label="Last name" name="lastName" required minLength={2} /></div><Field label="Personal email" name="personalEmail" type="email" required /><Field label="Mobile number (optional)" name="mobile" type="tel" /><Field label="City" name="city" required minLength={2} /><Field label="Create password" name="password" type="password" required minLength={10} /><label className="check"><input name="smsConsent" type="checkbox" /><span><b>Send me TeachersVIP updates by text.</b><small>By selecting this checkbox, you agree to receive recurring automated promotional texts from TeachersVIP. Consent is not required to join. Message and data rates may apply. Reply STOP to unsubscribe.</small></span></label>{error && <Notice kind="error">{error}</Notice>}<Button type="submit" disabled={busy}>{busy ? 'Creating account…' : 'Continue to Verification'}</Button></form><p className="switch">Already have an account? <Link to="/sign-in">Sign In</Link></p></AuthFrame>
}

function SignIn({ refresh }: { refresh: () => Promise<void> }) {
  const navigate = useNavigate(), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); const data = new FormData(event.currentTarget); try { await post('/auth/sign-in', { email: data.get('email'), password: data.get('password') }); await refresh(); navigate('/deals') } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  return <AuthFrame title="Welcome Back" intro="Sign in to your TeachersVIP account."><form className="form-grid" onSubmit={submit}><Field label="Personal email" name="email" type="email" required /><Field label="Password" name="password" type="password" required />{error && <Notice kind="error">{error}</Notice>}<Button type="submit" disabled={busy}>{busy ? 'Signing in…' : 'Sign In'}</Button></form><p className="switch">New to TeachersVIP? <Link to="/create-account">Create Account</Link></p></AuthFrame>
}

function Verify({ user, refresh }: { user: SessionUser; refresh: () => Promise<void> }) {
  const [params] = useSearchParams(), navigate = useNavigate(), [email, setEmail] = useState(user.work_email || ''), [message, setMessage] = useState(''), [error, setError] = useState(''), [devUrl, setDevUrl] = useState('')
  useEffect(() => { const token = params.get('token'); if (!token) return; post('/verification/confirm', { token }).then(async () => { await refresh(); setMessage('Your educator email is verified.'); setTimeout(() => navigate('/deals'), 900) }).catch(e => setError(e.message)) }, [params, navigate, refresh])
  const send = async (event: FormEvent) => { event.preventDefault(); setError(''); try { const result = await post<{ ok: boolean; verificationUrl?: string }>('/verification/send', { workEmail: email }); setMessage('Check your inbox and click the link to verify your email.'); setDevUrl(result.verificationUrl || '') } catch (e) { setError((e as Error).message) } }
  return <Page title="Verify Your Educator Email" narrow><div className="verify-panel"><div className="shield large">✓</div><p>Enter your official school or work email. For testing, all valid email domains are currently accepted.</p><form className="form-grid" onSubmit={send}><label className="field"><span>School/Work Email</span><input type="email" required value={email} onChange={e => setEmail(e.target.value)} /></label>{message && <Notice kind="success">{message}</Notice>}{error && <Notice kind="error">{error}</Notice>}<Button type="submit">Send Verification Link</Button>{devUrl && <a className="dev-link" href={devUrl}>Open development verification link</a>}</form><small>Your school/work email is used for verification only. No photo ID or school name is required.</small></div></Page>
}

function Shell({ user, onSignOut, children }: { user: SessionUser; onSignOut: () => Promise<void>; children: ReactNode }) {
  const location = useLocation(), links = [{ to: '/deals', label: 'Discover', Icon: Compass }, { to: '/saved', label: 'Saved', Icon: BookmarkSimple }, { to: '/vip-card', label: 'VIP Card', Icon: IdentificationCard }, { to: '/profile', label: 'Profile', Icon: UserCircle }]
  return <div className="app-shell"><aside className="desktop-nav"><Logo light /><nav>{links.map(({ to, label, Icon }) => <NavLink key={to} to={to}><Icon size={20} weight="duotone" />{label}</NavLink>)}</nav><div className="nav-user"><span>{user.first_name} {user.last_name}</span><small>{user.verified ? 'Verified Educator' : 'Verification pending'}</small><button onClick={onSignOut}>Sign out</button></div></aside><div className="app-main"><header className="topbar"><Logo /><span className={`status ${user.verified ? 'verified' : ''}`}><ShieldCheck size={14} weight="fill" />{user.verified ? 'Verified Educator' : 'Verification pending'}</span></header>{children}<nav className="mobile-nav" aria-label="Primary navigation">{links.map(({ to, label, Icon }) => <NavLink key={to} to={to} className={`${location.pathname.startsWith(to) ? 'active' : ''} ${to === '/vip-card' ? 'vip-nav' : ''}`}><span className="nav-icon"><Icon size={23} weight={location.pathname.startsWith(to) ? 'fill' : 'regular'} /></span><span>{label}</span></NavLink>)}</nav></div></div>
}
function Page({ title, children, narrow = false, action }: { title: string; children: ReactNode; narrow?: boolean; action?: ReactNode }) { return <main className={`page ${narrow ? 'page-narrow' : ''}`}><div className="page-heading"><div><span>TeachersVIP</span><h1>{title}</h1></div>{action}</div>{children}</main> }

function DealCard({ deal, onSave }: { deal: Deal; onSave: (deal: Deal) => void }) {
  return <article className="deal-card"><Link to={`/deals/${deal.id}`} onClick={() => void post('/analytics/events', { eventType: 'deal_view', businessId: deal.business_id, dealId: deal.id })}><div className="deal-image"><img src={deal.image_url} alt="" /><span className="channel">{deal.channel === 'online' ? 'Online' : 'In Person'}</span>{deal.sponsored && <span className="sponsored">Sponsored</span>}</div><div className="deal-copy"><small>{deal.category}</small><h2>{deal.business_name}</h2><strong>{deal.title}</strong><p>{deal.description}</p><div className="deal-meta">{deal.channel === 'in_person' ? <><span><MapPin size={15} weight="fill" />{deal.distance || deal.address || 'Local offer'}</span>{deal.hours && <span className={deal.is_open === false ? 'closed' : 'open'}><Clock size={15} weight="fill" />{deal.is_open == null ? deal.hours : `${deal.is_open ? 'Open' : 'Closed'} · ${deal.hours}`}</span>}</> : <span><Compass size={15} weight="fill" />Redeem online</span>}</div></div></Link><button className={`save ${deal.saved ? 'saved' : ''}`} aria-label={deal.saved ? 'Remove saved deal' : 'Save deal'} onClick={() => onSave(deal)}><Heart size={20} weight={deal.saved ? 'fill' : 'regular'} /></button></article>
}

function Discover() {
  const [deals, setDeals] = useState<Deal[]>([]), [q, setQ] = useState(''), [category, setCategory] = useState('All'), [error, setError] = useState(''), [loading, setLoading] = useState(true)
  const load = () => api<{ deals: Deal[] }>('/deals').then(r => { setDeals(r.deals); r.deals.forEach(d => void post('/analytics/events', { eventType: 'business_listing_view', businessId: d.business_id, dealId: d.id, idempotencyKey: `view-${d.id}-${new Date().toISOString().slice(0, 10)}` })) }).catch(e => setError(e.message)).finally(() => setLoading(false))
  useEffect(() => { void load() }, []); const categories = useMemo(() => ['All', ...new Set(deals.map(d => d.category))], [deals]), shown = deals.filter(d => (category === 'All' || d.category === category) && `${d.title} ${d.business_name}`.toLowerCase().includes(q.toLowerCase()))
  const toggle = async (deal: Deal) => { try { deal.saved ? await del(`/deals/${deal.id}/save`) : await post(`/deals/${deal.id}/save`); setDeals(v => v.map(d => d.id === deal.id ? { ...d, saved: !d.saved } : d)) } catch (e) { setError((e as Error).message) } }
  return <Page title="Discover Deals"><section className="hero"><span>EXCLUSIVE EDUCATOR PERKS</span><h2>Support local. Save more.</h2><p>Browse in-person and online offers made for educators.</p></section><div className="discovery-tools"><label className="search-wrap"><MagnifyingGlass size={20} /><input aria-label="Search deals" placeholder="Search businesses or offers" value={q} onChange={e => setQ(e.target.value)} /></label><div className="chips">{categories.map(c => <button className={category === c ? 'active' : ''} key={c} onClick={() => setCategory(c)}>{c}</button>)}</div></div>{error && <Notice kind="error">{error}</Notice>}{loading ? <DealSkeletons /> : <section className="deal-grid">{shown.map(d => <DealCard key={d.id} deal={d} onSave={toggle} />)}</section>}{!loading && !shown.length && <Empty title="No matching deals" text="Try a different search or category." />}</Page>
}

function DealDetail({ user }: { user: SessionUser }) {
  const { id } = useParams(), [deal, setDeal] = useState<Deal | null>(null), [code, setCode] = useState(''), [copied, setCopied] = useState(false), [reportResult, setReportResult] = useState<{ addedSavingsCents: number; estimatedSavingsCents: number; reportedUses: number } | null>(null), [error, setError] = useState('')
  useEffect(() => { api<{ deal: Deal }>(`/deals/${id}`).then(r => setDeal(r.deal)).catch(e => setError(e.message)) }, [id]); if (error && !deal) return <Page title="Deal"><Notice kind="error">{error}</Notice></Page>; if (!deal) return <Page title="Deal"><DetailSkeleton /></Page>
  const reveal = async () => { setError(''); try { const r = await post<{ promoCode: string }>(`/deals/${deal.id}/reveal-code`); setCode(r.promoCode) } catch (e) { setError((e as Error).message) } }
  const copyCode = async () => { try { await navigator.clipboard.writeText(code); setCopied(true); window.setTimeout(() => setCopied(false), 1800) } catch { setError('The promo code could not be copied. Press and hold the code to copy it manually.') } }
  const report = async () => { setError(''); try { const result = await post<{ addedSavingsCents: number; estimatedSavingsCents: number; reportedUses: number }>(`/deals/${deal.id}/report-use`, { idempotencyKey: crypto.randomUUID() }); setReportResult(result) } catch (e) { setError((e as Error).message) } }
  const directionsQuery = deal.latitude != null && deal.longitude != null ? `${deal.latitude},${deal.longitude}` : deal.address || deal.business_name
  return <Page title={deal.business_name} action={<Link className="back-link" to="/deals">Back to deals</Link>}><section className="deal-detail"><img src={deal.image_url} alt={`${deal.business_name} storefront or logo`} /><div className="detail-copy"><div className="tags"><span>{deal.channel === 'online' ? 'Online' : 'In Person'}</span><span>{deal.category}</span></div><h2>{deal.title}</h2><p>{deal.business_description}</p>{deal.channel === 'in_person' && deal.address && <p className="business-address">{deal.address}</p>}<div className="restriction"><b>Offer details and restrictions</b><span>{deal.restrictions}</span></div>{!user.verified && <Notice>Verify your educator email to access this offer.</Notice>}{reportResult ? <section className="report-success" role="status"><CheckCircle size={42} weight="fill" /><div><small>DEAL USE REPORTED</small><h3>{money(reportResult.addedSavingsCents)} added to your estimated savings</h3><p>You have reported {reportResult.reportedUses} {reportResult.reportedUses === 1 ? 'deal use' : 'deal uses'} and an estimated {money(reportResult.estimatedSavingsCents)} in savings.</p></div><div><Link className="action action-gold" to="/deals">Discover More Deals</Link><Link className="action action-soft" to="/profile">View My Savings</Link></div></section> : deal.channel === 'in_person' ? <div className="flow-actions"><Link className="action action-gold" to="/vip-card">Show VIP Card</Link><a className="action action-soft" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(directionsQuery)}`} target="_blank" rel="noreferrer" onClick={() => void post('/analytics/events', { eventType: 'directions_click', businessId: deal.business_id, dealId: deal.id })}>Get Directions</a><Button variant="navy" disabled={!user.verified} onClick={report}>I Used This Deal</Button></div> : <div className="flow-actions">{!deal.giveaway && (code ? <div className={`promo ${copied ? 'promo-copied' : ''}`}><span>Educator promo code</span><strong>{code}</strong><button onClick={copyCode}><Copy size={17} weight="bold" />{copied ? 'Copied' : 'Copy code'}</button></div> : <Button disabled={!user.verified} onClick={reveal}>Reveal Educator Promo Code</Button>)}{deal.website_url && <a className="action action-soft" href={deal.website_url} target="_blank" rel="noreferrer" onClick={() => void post('/analytics/events', { eventType: 'website_click', businessId: deal.business_id, dealId: deal.id })}>{deal.giveaway ? 'Visit Giveaway Page' : 'Visit Business Website'}</a>}{!deal.giveaway && <Button variant="navy" disabled={!user.verified} onClick={report}>I Used This Deal</Button>}</div>}{error && <Notice kind="error">{error}</Notice>}</div></section></Page>
}

function Saved() { const [deals, setDeals] = useState<Deal[]>([]), [loading, setLoading] = useState(true); const load = () => api<{ deals: Deal[] }>('/deals?saved=true').then(r => setDeals(r.deals)).finally(() => setLoading(false)); useEffect(() => { void load() }, []); const remove = async (deal: Deal) => { await del(`/deals/${deal.id}/save`); await load() }; return <Page title="Saved Deals">{loading ? <DealSkeletons count={2} /> : deals.length ? <section className="deal-grid">{deals.map(d => <DealCard key={d.id} deal={{ ...d, saved: true }} onSave={remove} />)}</section> : <Empty title="No saved deals yet" text="Save a deal to find it here later." action={<Link className="action action-navy" to="/deals">Explore Deals</Link>} />}</Page> }

function VipCard({ user }: { user: SessionUser }) {
  const [card, setCard] = useState<Card | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false); const load = () => api<{ card: Card }>('/me/vip-card').then(r => setCard(r.card)).catch(e => setError(e.message)); useEffect(() => { if (user.verified) void load() }, [user.verified])
  const addWallet = async () => { setBusy(true); setError(''); try { const result = await post<{ status: string; downloadUrl: string }>('/me/wallet-pass'); await load(); window.location.assign(result.downloadUrl) } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  const walletAction = card?.walletDownloadUrl ? <a className="action action-gold" href={card.walletDownloadUrl}>Open Wallet Card</a> : card?.walletStatus === 'not_configured' ? <Notice>Pass2U is not configured yet. Add its API key and model ID in Railway to enable automated card issuance.</Notice> : <Button disabled={busy} onClick={addWallet}>{busy ? 'Creating Wallet Card…' : 'Add to Wallet with Pass2U'}</Button>
  return <Page title="Your VIP Card" narrow>{!user.verified ? <Empty title="Verification required" text="Verify your school/work email before your personalized card is issued." action={<Link className="action action-gold" to="/verify">Verify Educator Email</Link>} /> : card ? <><section className="vip-card"><div className="card-brand"><Logo light /><span>VERIFIED EDUCATOR</span></div><div className="card-person"><small>MEMBER NAME</small><strong>{card.teacherName}</strong><small>MEMBER ID</small><b>{card.member_id}</b></div><div className="card-footer"><span>Verified Educator</span><span>Free for educators. Always.</span></div></section><div className="wallet-action">{walletAction}<small>Pass2U creates one personalized pass for this member. No NFC, loyalty, or Connected Passes data is included.</small></div></> : <p>Loading your personalized card…</p>}{error && <Notice kind="error">{error}</Notice>}</Page>
}

function ProfilePage({ onSignOut }: { onSignOut: () => Promise<void> }) {
  const [profile, setProfile] = useState<Profile | null>(null), [reports, setReports] = useState<any[]>([]), [editing, setEditing] = useState(false), [notice, setNotice] = useState(''); const load = async () => { const [p, r] = await Promise.all([api<{ profile: Profile }>('/me'), api<{ reports: any[] }>('/me/reported-uses')]); setProfile(p.profile); setReports(r.reports) }; useEffect(() => { void load() }, []); if (!profile) return <Page title="Profile"><p>Loading profile…</p></Page>
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const d = new FormData(event.currentTarget); await patch('/me', { firstName: d.get('firstName'), lastName: d.get('lastName'), mobile: d.get('mobile') || null, city: d.get('city'), smsConsent: d.get('smsConsent') === 'on' }); await load(); setEditing(false); setNotice('Personal information updated.') }
  return <Page title="Teacher Profile"><section className="profile-hero"><div className="avatar">{profile.first_name[0]}{profile.last_name[0]}</div><div><h2>{profile.first_name} {profile.last_name}</h2><span className={`status ${profile.educator_verified_at ? 'verified' : ''}`}>{profile.educator_verified_at ? 'Verified Educator' : 'Verification pending'}</span><p>{profile.member_id}</p></div></section><section className="stats"><div><strong>{money(profile.estimated_savings_cents)}</strong><span>Estimated Savings</span></div><div><strong>{profile.reported_uses}</strong><span>Reported Deal Uses</span></div><div><strong>{reports.length}</strong><span>Activity Records</span></div></section>{notice && <Notice kind="success">{notice}</Notice>}{editing ? <form className="profile-form form-grid" onSubmit={save}><div className="two"><Field label="First name" name="firstName" defaultValue={profile.first_name} required /><Field label="Last name" name="lastName" defaultValue={profile.last_name} required /></div><Field label="Personal email" name="email" defaultValue={profile.personal_email} type="email" readOnly /><Field label="Mobile number (optional)" name="mobile" defaultValue={profile.mobile || ''} /><Field label="City" name="city" defaultValue={profile.city} required /><label className="check"><input name="smsConsent" type="checkbox" defaultChecked={profile.sms_consent} /><span>Send me TeachersVIP updates by text.</span></label><Button type="submit">Save Changes</Button><Button variant="soft" onClick={() => setEditing(false)}>Cancel</Button></form> : <div className="profile-actions"><Button variant="soft" onClick={() => setEditing(true)}>Edit Personal Information</Button><Link className="action action-soft" to="/vip-card">Show VIP Card</Link><Link className="action action-soft" to="/support">Help &amp; Support</Link><Link className="action action-soft" to="/partner">Partner With Us</Link><Button variant="danger" onClick={() => void onSignOut()}>Sign Out</Button></div>}<section className="history"><h2>Reported Deal Uses</h2>{reports.length ? reports.map(r => <div className="history-row" key={r.id}><span><b>{r.business_name}</b><small>{new Date(r.reported_at).toLocaleDateString()}</small></span><strong>{money(r.estimated_savings_cents)} estimated</strong></div>) : <p>No reported deal uses yet.</p>}</section></Page>
}

function Partner() { const [sent, setSent] = useState(false), [error, setError] = useState(''); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const d = new FormData(event.currentTarget); try { await post('/partner-inquiries', { businessName: d.get('businessName'), businessEmail: d.get('businessEmail'), proposedDeal: d.get('proposedDeal') }); setSent(true) } catch (e) { setError((e as Error).message) } }; return <Page title="Partner With Us" narrow>{sent ? <Empty title="Interest received" text="TeachersVIP will manually review the information and contact the business." action={<Link className="action action-gold" to="/profile">Back to Profile</Link>} /> : <form className="partner-card form-grid" onSubmit={submit}><p>Interested businesses can leave their details for manual onboarding.</p><Field label="Business name" name="businessName" required /><Field label="Business email" name="businessEmail" type="email" required /><label className="field"><span>Deal you would like to offer</span><textarea name="proposedDeal" required minLength={5} /></label>{error && <Notice kind="error">{error}</Notice>}<Button type="submit">Send Interest</Button></form>}</Page> }
function Support() {
  const [query, setQuery] = useState(''), [open, setOpen] = useState(0)
  const faqs = [
    { question: 'How do I use an in-person deal?', answer: 'Open the deal, review its restrictions, and tap Show VIP Card. Present your personalized card at checkout, then use I Used This Deal to add the estimated saving to your profile.' },
    { question: 'How do online promo codes work?', answer: 'Verified educators can reveal and copy the educator promo code from an online deal. Use it on the business website, then report the deal use in TeachersVIP.' },
    { question: 'What email can I use for verification?', answer: 'During testing, any valid email address is accepted as the school/work email. Domain validation can be enabled before the public launch.' },
    { question: 'Do I need Apple Wallet or Google Wallet?', answer: 'No. Your VIP card is always available directly in TeachersVIP. The Pass2U wallet card is an optional shortcut for quicker access.' },
    { question: 'How are estimated savings calculated?', answer: 'Savings are based on the amount assigned to each deal and the uses you report. They are estimates, not confirmed purchases or payment records.' },
  ]
  const shown = faqs.filter(item => `${item.question} ${item.answer}`.toLowerCase().includes(query.toLowerCase()))
  return <Page title="Help & Support" narrow><section className="support-intro"><div className="support-icon"><Question size={30} weight="duotone" /></div><div><h2>How can we help?</h2><p>Quick answers for your account, educator card, and deal redemptions.</p></div></section><label className="search-wrap support-search"><MagnifyingGlass size={20} /><input aria-label="Search help topics" placeholder="Search help topics" value={query} onChange={event => setQuery(event.target.value)} /></label><section className="faq-list">{shown.map((item, index) => { const expanded = open === index && !query; return <article className={`faq ${expanded ? 'open' : ''}`} key={item.question}><button aria-expanded={expanded} onClick={() => setOpen(expanded ? -1 : index)}><span>{item.question}</span><span aria-hidden="true">+</span></button>{(expanded || query) && <p>{item.answer}</p>}</article> })}</section>{!shown.length && <Empty title="No matching help topic" text="Try a shorter search phrase." />}<section className="support-partner"><div><small>FOR BUSINESSES</small><h3>Want to offer an educator perk?</h3><p>TeachersVIP manually reviews and onboards participating businesses.</p></div><Link className="action action-gold" to="/partner">Partner With Us</Link></section></Page>
}
function DealSkeletons({ count = 4 }: { count?: number }) { return <section className="deal-grid" aria-label="Loading deals">{Array.from({ length: count }, (_, index) => <div className="deal-card skeleton-card" key={index}><div className="skeleton skeleton-image" /><div className="skeleton-copy"><span className="skeleton short" /><span className="skeleton title" /><span className="skeleton medium" /><span className="skeleton line" /></div></div>)}</section> }
function DetailSkeleton() { return <div className="detail-skeleton" aria-label="Loading deal"><div className="skeleton detail-image" /><div className="skeleton-copy"><span className="skeleton short" /><span className="skeleton title" /><span className="skeleton line" /><span className="skeleton line" /><span className="skeleton button" /></div></div> }
function Empty({ title, text, action }: { title: string; text: string; action?: ReactNode }) { return <section className="empty"><div className="empty-emblem"><ShieldCheck size={34} weight="duotone" /></div><h2>{title}</h2><p>{text}</p>{action}</section> }

function AppRoutes() {
  const [loading, setLoading] = useState(true), [user, setUser] = useState<SessionUser | null>(null), navigate = useNavigate(); const refresh = useCallback(async () => { const r = await api<{ user: SessionUser | null }>('/auth/session'); setUser(r.user) }, []); useEffect(() => { refresh().finally(() => setLoading(false)) }, [refresh]); const signOut = async () => { await post('/auth/sign-out'); setUser(null); navigate('/sign-in') }; if (loading) return <div className="splash"><Logo light /><span>Loading TeachersVIP…</span></div>
  return user ? <Shell user={user} onSignOut={signOut}><Routes><Route path="/verify" element={<Verify user={user} refresh={refresh} />} /><Route path="/deals" element={<Discover />} /><Route path="/deals/:id" element={<DealDetail user={user} />} /><Route path="/saved" element={<Saved />} /><Route path="/vip-card" element={<VipCard user={user} />} /><Route path="/profile" element={<ProfilePage onSignOut={signOut} />} /><Route path="/support" element={<Support />} /><Route path="/partner" element={<Partner />} /><Route path="*" element={<Navigate to="/deals" replace />} /></Routes></Shell> : <Routes><Route path="/create-account" element={<Register refresh={refresh} />} /><Route path="/sign-in" element={<SignIn refresh={refresh} />} /><Route path="*" element={<Navigate to="/create-account" replace />} /></Routes>
}
export default function App() { return <BrowserRouter><AppRoutes /></BrowserRouter> }
